<?php
/**
 * Implementation of hook_block().
 */
function balanceonline_contact_person_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Custom Contact Person');
    $blocks[0]['cache'] = BLOCK_NO_CACHE;
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        return balanceonline_contact_person_block_details();
    }
  }
}

function balanceonline_contact_person_block_details() {
  $node = node_load(arg(1));
	if($node->field_projectaccount[0]['uid']){
		$account = user_load($node->field_projectaccount[0]['uid']);
		$userobj = unserialize($account->data);
		if(empty($account->picture)) {
		  $account->picture = 'dummy.jpg';
		}

		$content = l($content .= theme('imagecache', 'userpic-1c-square', $account->picture, 'Bild', t('Ansprechpartner', NULL, 'de')).'<br />' .  $account->profile_title.' '.$account->profile_firstname.' '.$account->profile_lastname . '</a><br />', 'user/' . $account->uid, array('html' => TRUE));

		if($userobj['addresses']['phone']){
			$content .= t('Telefon', NULL, 'de') . ': ' . $userobj['addresses']['phone'] . '<br />';
		}
    $content .= l(t('Kontaktieren', NULL, 'de'), 'user/' . $account->uid . '/contact');
		
		$block['content'] = $content;
    $block['subject'] = t('Ansprechpartner', NULL, 'de');
    return $block;
	}
}
